import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSelector, useDispatch } from "react-redux";
import { decrement, increment, selectValue } from "../slices/counterSlice";
import type { RootState } from "../store";

export default function Home() {
  const count = useSelector(selectValue);
  const dispatch = useDispatch();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl">value of count is {count}</h1>
        <button onClick={() => dispatch(increment())}>Inc</button>
        <button onClick={() => dispatch(decrement())}>dec</button>
      </main>
    </div>
  );
}
